### ISSUE TITLE
Led Matrix and Spectrum analyser

### ISSUE THREAD

**Issue by Sebastianopazo** [yoyojacky/52Pi#1]
Hi! 

I'm very new to Rpi, gpio, etc. 
I have this led 8x8 matrix and I was wondering what you'd recommend to use it as an audio visualizer. 

Best

**Comment by yoyojacky** [comment]
hi! thanks for your message, and i recommend that you first using a tool to analyze the audio's PWM pulse and convert it to a array, and then send the array to the program that driver the 8x8 matrix.
