### ISSUE TITLE
Rotate 5 inch capacicative 800x480 screen

### ISSUE THREAD

**Issue by maciekish** [yoyojacky/52Pi#2]
Hi,
How can i rotate the screen upside down? The standard Raspberry Pi config/cmdline.txt doesn't work.

**Comment by yoyojacky** [comment]
It depends on your system, not the display,  so, if you are using Raspbian as your OS. you may need to change the configuration file as following command: 

> sudo nano /boot/config.txt

and add one of these to the bottom:

display_rotate=0 Normal
display_rotate=1 90 degrees
display_rotate=2 180 degrees
NOTE: You can rotate both the image and touch interface 180º by entering lcd_rotate=2 instead
display_rotate=3 270 degrees
display_rotate=0x10000 horizontal flip
display_rotate=0x20000 vertical flip
