### ISSUE TITLE
8x8 LED matrix help

### ISSUE THREAD

**Issue by alwye** [yoyojacky/52Pi#3]
Hi @yoyojacky 

I've seen your post on https://wiki.52pi.com/index.php/RPI-RGB-LED-Matrix_SKU:EP-0075

It's been very informative, and I'm trying to adapt your code to my use case. I was wondering if you could help me out.

First of all, I'm using an ESP8266 microcontroller with the MicroPython firmware. I have somewhat adapted your code to MicroPython and looks like this:

```Python
from machine import SPI, Pin
import time

spi = SPI(1, baudrate=500000)
ce = Pin(15, Pin.OUT, value=1)

rows = [0x00, 0x66, 0xFF, 0xFF, 0xFF, 0x7E, 0x3C, 0x18]
for j in range(8):
    ce.off()
    spi.write(bytearray([~rows[j], 0xFF, 0xFF, 0x01 << j]))
    ce.on()
    time.sleep(0.1)
```

For some reason, every time it draws a horizontal line, the previous line disappears. I've recorded a video: https://youtu.be/KMouz8hCJDg

I was wondering if you have an idea what I may need to change in my code in order to make the matrix display the full picture.

Thank you.

**Comment by alwye** [comment]
If the last line sets ```time.sleep``` to 0.02, then flickering is minimal, but it still occurs. I'm not sure if that's supposed to be a correct mode of operation or not.

**Comment by yoyojacky** [comment]
it seems like that your MCU turn on and off the light may have a delay, so that you will see the flickering, if you time.sleep duration is less than 0.02s, it may cause the dim light, because it have not enough time to charge the LED...

**Comment by yoyojacky** [comment]
> If the last line sets `time.sleep` to 0.02, then flickering is minimal, but it still occurs. I'm not sure if that's supposed to be a correct mode of operation or not.

spi speed setting higher and change "delay" to "pass" statement, and try again?

**Comment by alwye** [comment]
Thanks!
